import './globals.css'
import { Inter } from 'next/font/google'
import Toaster from '@/components/Toast'
import AuthProvider from '@/providers/AuthProvider';
import CartProvider from '@/providers/CartProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shop-Now | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark" className="transition-all">
      <body className={inter.className}>

        <CartProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </CartProvider>


        <Toaster />

      </body>
    </html>
  )
}
